# Generated by Django 4.2 on 2023-05-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='page_name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
